version: '3'
services:
  database:
    container_name: database_receiver
    image: 'docker.io/bitnami/postgresql:11-debian-10'
    volumes:
      - 'database:/bitnami/postgresql'
    environment:
      POSTGRESQL_USERNAME: spring
      POSTGRESQL_PASSWORD: 1234
      POSTGRESQL_POSTGRES_PASSWORD: 1234
      POSTGRESQL_DATABASE: "turbex_receiver_service"
    ports:
      - "5475:5432"
    networks:
      - application_ds
  redis:
    container_name: redis_ds
    image: 'docker.io/bitnami/redis:6.0-debian-10'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      - application_ds
networks:
  application_ds:
    driver: bridge
volumes:
  redis_data:
    driver: local
  database:
    driver: local