
server:
  port: 8700

spring:
  application:
      name: "ReceiverService"
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5475/turbex_receiver_service}
    username: "spring"
    password: 1234
    jpa:
      show-sql: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL9Dialect
      hibernate:
        ddl-auto: update